'''
389. Find the Difference
Easy

String t is generated by random shuffling string s and then add one more letter at a random position. Find the letter that was added in t.

Solution:

	1. expect_sum - actual_sum

	2. XOR
'''

class Solution1:
    def findTheDifference(self, s: str, t: str) -> str:
        ans = ord(t[-1])
        for a, b in zip(s, t):
            ans += ord(b) - ord(a)
        return chr(ans)

class Solution2:
    def findTheDifference(self, s: str, t: str) -> str:
        ans = 0
        for c in s + t:
            ans ^= ord(c)
        return chr(ans)